server:
  port: 8080
spring:
  application:
    name: eureka-zuul
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

zuul:
  ignored-services: '*'
  routes:
    rout1:
      serviceId: eureka-provider
      path: /provider/**
#    eureka-customer:
#      path: /ec/**
    eureka-customer: /customer/**
  ribbon:
    eager-load:
      enabled: true
  SendResponseFilter:
    pre:
      disable: true

